### ISSUE TITLE
BAIT setup

### ISSUE THREAD

**Issue by vincent-hanlon** [mattsada/sspipe#1]
BAIT doesn't work with Samtools version 1.9, but it does work with Samtools 0.1.19. Installing the old Samtools and changing SAMPATH in BAIT from "samtools" to "path/to/samtools/0.1.19/executable/samtools" fixes this issue.

Three more R packages are also required to run BAIT: changepoint, DNAcopy, and GenomicRanges

**Comment by mattssca** [comment]
Dependency-list updated
