### ISSUE TITLE
Error in 11-datavis.R

### ISSUE THREAD

**Issue by vincent-hanlon** [mattsada/sspipe#10]
I reported this earlier as an error when running with too many files (because that's what I was testing with) but it turns out to be an error for even just 5 files that causes 11-datavis to crash so it won't produce figures.

Error: Dimensions exceed 50 inches (height and width are specified in 'in' not pixels). If you're sure you want a plot that big, use `limitsize = FALSE`.
Execution halted

**Comment by mattssca** [comment]
Added `limitsize = FALSE` to ggsave() argument.
