### ISSUE TITLE
Outstanding issues from the last round of debugging

### ISSUE THREAD

**Issue by vincent-hanlon** [mattsada/sspipe#12]
1. The “How to execute” instructions are to gunzip the FASTQ files before running SSPIPE, but the script is set up to handle gzipped files.

2. The path to the picard.jar file is set to something on Adam’s computer, and there are no instructions for how to replace it (or what with). This is a problem for multiple scripts. The user should either input the path to his or her jarfile as an argument or following a prompt, or there should be instructions as to how to edit the scripts and which scripts to edit (in the "How to execute" section, maybe?).

3. The script 04-mark-dup-picard.sh still crashes because it is looking for *.bam files not *.sorted files, which are what the previous script outputs.

4. The indexing script generates extra empty *.bai files that aren't used (as well as real *bai files that _are_ used

**Comment by mattssca** [comment]
Raised Issues has been resolved
