### ISSUE TITLE
09-gc-bias-picard.sh index name

### ISSUE THREAD

**Issue by vincent-hanlon** [mattsada/sspipe#13]
The name of the index in the gc bias script doesn't match the name of the index output by get_refseq.sh. In 09-gc-bias-picard.sh, "R=./refseq/bowtie2.GCHr38.fasta" should be changed to "R=./refseq/GRCh38.fasta"

**Comment by mattssca** [comment]
This issue was solved in the June 21 push. Could you check when you pulled the repository last time? Should be fixed.

**Comment by mattssca** [comment]
Feel free to close the issue if working

**Comment by vincent-hanlon** [comment]
Sounds good---my copy was a few days older than that
