### ISSUE TITLE
MarkDuplicates output and the alignment plots disagree

### ISSUE THREAD

**Issue by vincent-hanlon** [mattsada/sspipe#14]
There is a discrepancy between the main alignment plot generated by sspipe (sspipe/figs/alignment_qc.pdf; also sspipe/metrics/alignmentmetrics.txt) and the raw MarkDuplicates output (in sspipe/metrics/mdup). Using my current batch of libraries as an example: in the former, %duplicate values range from 0.089% to 47.6% (mean 24.1%); in the latter, values range from 0.18% to 94.6% (mean 47.3%).

**Comment by mattssca** [comment]
This issue has now been resolved. Thank you!
