### ISSUE TITLE
# duplicate reads incorrect

### ISSUE THREAD

**Issue by vincent-hanlon** [mattsada/sspipe#16]
In "sspipe/figs/alignment_qc.pdf", the plot title "1. Alignment summary" contains data of the number of read duplicates (in orange).

These numbers are currently calculated this way:
READ_PAIR_DUPLICATES + UNPAIRED_READ_DUPLICATES

However, this gives the wrong value for the number of read duplicates, because each READ_PAIR_DUPLICATE contains **two** reads. 

So it should be calculated like this:
READ_PAIR_DUPLICATES*2 + UNPAIRED_READ_DUPLICATES

**Comment by mattssca** [comment]
The issue has been resolved, thank you for your comments Vincent
