### ISSUE TITLE
11-datavis.R setup

### ISSUE THREAD

**Issue by vincent-hanlon** [mattsada/sspipe#3]
Required R packages include ggthemes, kableExtra, and gridExtra. tableGrob is also listed as a required library, but it isn't a library. The line “library(“tableGrob”)” needs to be removed from the R script if it is to work.

I also had to add a setwd() statement (see the issue for 10-dataman.R), and change the path in ggsave to 

path = "../figs", 

with the quotes before the comma and with ".." rather than "." before "/figs"

**Comment by mattssca** [comment]
list of R packages updated, tableGrob line removed and updated ggsave path.
