### ISSUE TITLE
get_refseq.sh throws error

### ISSUE THREAD

**Issue by vincent-hanlon** [mattsada/sspipe#6]
When I run get_refseq.sh it produces this error:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/bowtie2-inspect", line 83, in <module>
    main()
  File "/home/linuxbrew/.linuxbrew/bin/bowtie2-inspect", line 80, in main
    sys.exit(subprocess.call(argv))
NameError: global name 'sys' is not defined

The files hg38.fa and GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.tar seem to be complete, but bowtie2.GCHr38.fasta is empty. I'm not sure whether it's meant to produce any other files.

**Comment by vincent-hanlon** [comment]
Also, minor note: the script doesn't un-tar GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.tar, but it easily could----just use "tar -zxvf" rather than "gunzip"

**Comment by mattssca** [comment]
Thanks for raising this issue Vincent. That's probably the issue then. If the script doesn't un-tar the GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.tar file. I don't believe that line 14 in get_refseq.sh would execute properly, the output file would be empty. The script has been updated, pls try again :)

**Comment by vincent-hanlon** [comment]
It does probably help, but it doesn't fix the issue. It looks as though the file you're trying to convert back to FASTA doesn't exist (or the filename is wrong)

**Comment by mattssca** [comment]
I've updated the output path of un-tared reference genome and the script works at my end (also, cd needs to be set to sspipe main folder in order for it to work).

**Comment by vincent-hanlon** [comment]
It looks as though you've inadvertently also deleted the lines that download the hg38 reference...

**Comment by mattssca** [comment]
I did that because I thought it was redundant to have two GRCh38 genomes in fasta (the script should now generate a fasta from the bowtie indexed reference genome).

I've updated the path to reference genome for those scripts that require this in .fasta format (05-align-met-picard.sh and 09-gc-bias-picard.sh). Let me know if you find out any other conflicts.

**Comment by vincent-hanlon** [comment]
Ok, so it was intentional! That's good.

I'll keep my hg38.fa for now and use that, since otherwise I'd have to download sspipe again and go through setup. 

Are the two FASTA genomes really the same? If so, why bother converting the Bowtie2 index file? If not, do we know that using a non-standard converted reference won't change alignments?

**Comment by mattssca** [comment]
Sounds good. 

Here are my thoughts. Bowtie2 indexed genome has some additional content, such as mitochondrial DNA and decoys. Since this build is used for the alignment the scripts that are dependent on a reference genome needs to have the same additional content, even though there’s nothing there. Does that make sense? 

This could be worked around by using a different aligner, one that takes standard FASTA as reference genome. Alternatively, I could compile a different b2t genome with only chr1-22:xy

**Comment by vincent-hanlon** [comment]
Yep agreed about the index. I guess I'm wondering whether hg38.fa was used for anything at all in the previous version, but it sounds like not? In this case I agree, much simpler.

**Comment by mattssca** [comment]
Hg38.fa was used in two metrics-script (05-align-met-Picard.sh and 09-gc-bias-picard.sh). I’ve updated those scripts to use the exact ref genome (but in fasta) that we use in the alignment. 

If it’s unclear I’d be happy to explain Monday! I’ll try to solve the other issues this weekend. Thanks for keeping an eye out and creating issues here, much appreciated.

**Comment by vincent-hanlon** [comment]
No worries---and thanks, I know you just mentioned 05 and 06, but I missed that somehow. Too much running around in the lab.

Also, sorry, just realized my question a few comments up ("do we know that using a non-standard converted reference won't change alignments?") was totally backwards. No issues with using an indexed reference. Really I meant to ask whether it would conflict with other uses of the FASTA reference-----but you've just answered that.

**Comment by vincent-hanlon** [comment]
Ok, turns out this does not fix the error from the first comment, so the script doesn't produce the FASTA genome.

I know you're in the process of setting up ORCA---maybe the thing to do is see then whether you get the same error?

**Comment by vincent-hanlon** [comment]
I looked into this error further, and there's good news----it's specific to one (or possibly a few) versions of bowtie2. The error occurs with v2.3.4.2, but upgrading to v.2.3.5 fixes it.

**Comment by mattssca** [comment]
Yeah, I suspected something like that. I'm glad you've figured it out.
